services:
  - type: web
    name: sync-chatapp-backend
    env: go
    plan: free
    buildCommand: go build -o main main.go
    startCommand: ./main
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GIN_MODE
        value: release
